name: build-noble

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd scripts
          sed -i -E 's/TARGET_UBUNTU_VERSION=(.*)/TARGET_UBUNTU_VERSION="noble"/g' default_config.sh
          ./build.sh -
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-pbx
          path: |
            scripts/ubuntu-pbx.iso
            scripts/image/md5sum.txt
